
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/trainingdb
    username: root
    password: aniruddha
# below are optional properties
# you may neglect, it is just for logging purpose
  jpa:
    show-sql: true
    properties:
       hibernate.format_sql: true
    